version: '2.4'
services:
    configserver:
        build: ./configserver
        network_mode: "host"
        environment:
            CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
        image: configserver:latest
        restart: always
        ports:
            - 8888:8888
        logging:
            options:
                max-size: "10m"
                max-file: "10"

    eurekaserver:
        build: ./eurekaserver
        network_mode: "host"
        environment:
            CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
        image: eurekaserver:latest
        restart: always
        depends_on:
            configserver:
                condition: service_healthy
        ports:
            - 8761:8761
        logging:
            options:
                max-size: "10m"
                max-file: "10"

    view:
        build: ./view
        network_mode: "host"
        environment:
            CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
        image: view:latest
        restart: always
        depends_on:
            configserver:
                condition: service_healthy
            eurekaserver:
                condition: service_healthy
        ports:
            - 8080:8080
        logging:
            options:
                max-size: "10m"
                max-file: "10"

    database:
        build: ./database
        network_mode: "host"
        environment:
            CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
        image: database:latest
        restart: always
        depends_on:
            configserver:
                condition: service_healthy
            eurekaserver:
                condition: service_healthy
        ports:
            - 4711:4711
        logging:
            options:
                max-size: "10m"
                max-file: "10"

    timescaledb-reader:
        build: ./timescaleDbReader
        network_mode: "host"
        environment:
            CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
        image: timescaledb-reader:latest
        restart: always
        depends_on:
            configserver:
                condition: service_healthy
            eurekaserver:
                condition: service_healthy
        ports:
            - 4720:4720
        logging:
            options:
                max-size: "10m"
                max-file: "10"

    timescaledb-writer:
        build: ./timescaleDbWriter
        network_mode: "host"
        environment:
            CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
        image: timescaledb-writer:latest
        restart: always
        depends_on:
            configserver:
                condition: service_healthy
            eurekaserver:
                condition: service_healthy
            timescaledb-reader:
              condition: service_healthy
        ports:
            - 4721:4721
        logging:
            options:
                max-size: "10m"
                max-file: "10"

    mqttclient:
        build: ./mqttclient
        network_mode: "host"
        environment:
            CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
        image: mqttclient:latest
        restart: always
        depends_on:
            configserver:
                condition: service_healthy
            eurekaserver:
                condition: service_healthy
            timescaledb-writer:
              condition: service_healthy
        ports:
            - 1883:1883
        logging:
            options:
                max-size: "10m"
                max-file: "10"
