spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/db-name"
        username: "user"
        password: "pass"
        driverClassName: "org.postgresql.Driver"

    jpa:
        properties:
            hibernate:
                dialect: "org.hibernate.dialect.PostgreSQL95Dialect"
                ddl-auto: "validate"
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

logging:
    level:
        com.netflix.discovery: 'INFO'
        org.springframework.cloud: 'DEBUG'
        org.springframework.security: 'INFO'

server:
    port: 4721
