spring:
    datasource:
        url: "jdbc:postgresql://localhost/msg"
        username: "msg"
        password: "msg"
        driverClassName: "org.postgresql.Driver"

eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

server:
    port: 4721
