spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/msg"
        username: "msg"
        password: "msg"

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                ddl-auto: validate
                physical_naming_strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy
        generate-ddl: true
        show-sql: true


eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

logging:
    level:
        com.netflix.discovery: 'INFO'
        org.springframework.cloud: 'DEBUG'
        org.springframework.security: 'INFO'

server:
    port: 4721
