spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/<db-name>"
        username: "<user>"
        password: "<pass>"
        driverClassName: "org.postgresql.Driver"

    jpa:
        properties:
            hibernate:
                dialect: "org.hibernate.dialect.PostgreSQL95Dialect"
                ddl-auto: "validate"
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

server:
    port: 4721
