server:
    port: 8761

spring:
    application:
        name: eurekaserver

eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    server:
        waitTimeInMsWhenSyncEmpty: 0

logging:
    level:
        com.netflix.discovery: 'INFO'
        org.springframework.cloud: 'DEBUG'
        org.springframework.security: 'INFO'
