spring:
    cloud:
        config:
            server:
                native:
                    search-locations: classpath:/shared
    profiles:
        active: native
    security:
        user:
            password: ${CONFIG_SERVICE_PASSWORD}

server:
    port: 8888

logging:
    level:
        com.netflix.discovery: 'INFO'
        org.springframework.cloud: 'DEBUG'
        org.springframework.security: 'INFO'

eureka:
    instance:
        leaseRenewalIntervalInSeconds: 10
        statusPageUrlPath: /admin/info
        healthCheckUrlPath: /admin/health
