spring:
    datasource:
        url: "jdbc:postgresql://192.168.121.10:5432/msg"
        username: "postgres"
        password: "postgres"

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                ddl-auto: none
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

server:
    port: 4720
