spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/db-name"
        username: "user"
        password: "pass"

    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL95Dialect
                ddl-auto: none
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

server:
    port: 4720
